project 'DropBox.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'DropBox' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DropBox
 pod "SwiftyDropbox"
end
